project:
  type: website
  output-dir: docs

website:
  title: "holisticbi.com"
  favicon: "assets/logo-powerbi.png"
  navbar:
    background: primary
    right:
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/pomegranatebee/
  page-footer:
    left: |
      *Copyright {{< var year >}} | [<span class="blue-text">Caleb Kirsch</span>](about.qmd)*
format:
  html:
    theme:
      dark: darkly
      light: flatly
    fontsize: medium
    css: styles.css

jupyter: .venv/Scripts/python

