project:
  type: website
  output-dir: docs

website:
  title: "holisticbi.com"
  navbar:
    background: primary
    right:
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/pomegranatebee/
  page-footer:
    left: |
      *This website is built with [![](assets/logo-quarto.png){width=80px}](https://quarto.org/) and hosted via [GitHub Pages](https://github.com/pomegranatebee/pomegranatebee.github.io)*
format:
  html:
    theme:
      dark: darkly
      light: flatly
    fontsize: medium
    css: styles.css



