project:
  type: website
  output-dir: docs

website:
  title: "holisticbi.com"
  favicon: "assets/logo-powerbi.png"
  navbar:
    background: primary
    right:
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/pomegranatebee/
  page-footer:
    left: |
      *This website is built with [Quarto](https://quarto.org/) and hosted via [GitHub Pages](https://github.com/pomegranatebee/pomegranatebee.github.io)*
format:
  html:
    theme:
      dark: darkly
      light: flatly
    fontsize: medium
    css: styles.css

jupyter: .venv/Scripts/python

